# Generated by Django 4.2 on 2023-05-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categorytype', models.CharField(choices=[('DRINKS', 'Drinks'), ('FOOD', 'Food')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(max_length=50)),
                ('stockcategory', models.CharField(choices=[('INGR', 'Ingredients'), ('AO', 'AddOns'), ('UTNSL', 'Utensils')], max_length=100)),
                ('stockquantity', models.PositiveIntegerField()),
                ('stockmeasurement', models.CharField(choices=[('G', 'Grams'), ('PCS', 'Pieces'), ('ML', 'MiliLiters')], max_length=100)),
                ('stockprice', models.FloatField()),
                ('stockdate_in', models.DateField()),
                ('stockexpiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.CharField(max_length=100)),
                ('menuIngrPrice1', models.FloatField(blank=True, null=True)),
                ('menuIngrPrice2', models.FloatField(blank=True, null=True)),
                ('menuIngrPrice3', models.FloatField(blank=True, null=True)),
                ('menuIngrPrice4', models.FloatField(blank=True, null=True)),
                ('menuIngrPrice5', models.FloatField(blank=True, null=True)),
                ('menuAOPrice1', models.FloatField(blank=True, null=True)),
                ('menuAOPrice2', models.FloatField(blank=True, null=True)),
                ('menuAOPrice3', models.FloatField(blank=True, null=True)),
                ('menuAOPrice4', models.FloatField(blank=True, null=True)),
                ('menuAOPrice5', models.FloatField(blank=True, null=True)),
                ('menuimage', models.ImageField(upload_to='mema/')),
                ('menuprice', models.FloatField()),
                ('sugarlevel', models.BooleanField(default=False)),
                ('alcohollevel', models.BooleanField(default=False)),
                ('quantityIng1', models.PositiveIntegerField()),
                ('quantityIng2', models.PositiveIntegerField()),
                ('quantityIng3', models.PositiveIntegerField()),
                ('quantityIng4', models.PositiveIntegerField()),
                ('quantityIng5', models.PositiveIntegerField()),
                ('quantityAO1', models.PositiveIntegerField()),
                ('quantityAO2', models.PositiveIntegerField()),
                ('quantityAO3', models.PositiveIntegerField()),
                ('quantityAO4', models.PositiveIntegerField()),
                ('quantityAO5', models.PositiveIntegerField()),
                ('addons1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons1', to='pos.stocks')),
                ('addons2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons2', to='pos.stocks')),
                ('addons3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons3', to='pos.stocks')),
                ('addons4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons4', to='pos.stocks')),
                ('addons5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons5', to='pos.stocks')),
                ('ingredient1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient1', to='pos.stocks')),
                ('ingredient2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient2', to='pos.stocks')),
                ('ingredient3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient3', to='pos.stocks')),
                ('ingredient4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient4', to='pos.stocks')),
                ('ingredient5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient5', to='pos.stocks')),
                ('menucategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.menucategory')),
            ],
        ),
    ]
