# Generated by Django 4.2 on 2023-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='transaction',
            field=models.BooleanField(default=False),
        ),
    ]
