# Generated by Django 4.2.1 on 2023-05-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='menuAOPrice1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='menuAOPrice2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='menuAOPrice3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='menuAOPrice4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='menuAOPrice5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
