# Generated by Django 4.2 on 2023-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudrinks',
            name='HotandCold',
            field=models.BooleanField(default=False),
        ),
    ]
