# Generated by Django 4.2 on 2023-05-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudrinks',
            name='menuAOPrice1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuAOPrice1', to='pos.stocks'),
        ),
        migrations.AddField(
            model_name='menudrinks',
            name='menuAOPrice2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuAOPrice2', to='pos.stocks'),
        ),
        migrations.AddField(
            model_name='menudrinks',
            name='menuAOPrice3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuAOPrice3', to='pos.stocks'),
        ),
        migrations.AddField(
            model_name='menudrinks',
            name='menuAOPrice4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuAOPrice4', to='pos.stocks'),
        ),
        migrations.AddField(
            model_name='menudrinks',
            name='menuAOPrice5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuAOPrice5', to='pos.stocks'),
        ),
    ]
