# Generated by Django 4.2 on 2023-06-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudrinks',
            name='question1',
            field=models.BooleanField(default=False),
        ),
    ]
