# Generated by Django 4.2 on 2023-05-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_menudrinks_menuaoprice1_menudrinks_menuaoprice2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudrinks',
            name='menuAOPrice1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuAOPrice2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuAOPrice3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuAOPrice4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuAOPrice5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuIngrPrice1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuIngrPrice2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuIngrPrice3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuIngrPrice4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='menuIngrPrice5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
