# Generated by Django 4.2 on 2023-06-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_menudrinks_question1'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudrinks',
            name='question2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menudrinks',
            name='question3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menudrinks',
            name='question4',
            field=models.BooleanField(default=False),
        ),
    ]
