# Generated by Django 4.2.1 on 2023-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_rename_ordernumber_buyitem_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='dateordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
