# Generated by Django 4.2 on 2023-07-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='stockmeasurement',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='stockquantity',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
