# Generated by Django 4.2 on 2023-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_menudrinks_hotandcold'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudrinks',
            name='hotAndCold',
            field=models.BooleanField(default=False),
        ),
    ]
