# Generated by Django 4.2.1 on 2023-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_buyitem_dateordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='DoneOrder',
            field=models.BooleanField(default=False),
        ),
    ]
