# Generated by Django 4.2.1 on 2023-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_menudrinks_question2_menudrinks_question3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudrinks',
            name='q1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menudrinks',
            name='q2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menudrinks',
            name='q3',
            field=models.BooleanField(default=False),
        ),
    ]
