# Generated by Django 4.2 on 2023-05-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_menudrinks_hotandcold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityAO1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityAO2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityAO3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityAO4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityAO5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityIng1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityIng2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityIng3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityIng4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menudrinks',
            name='quantityIng5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
