# Generated by Django 4.2.1 on 2023-05-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_buyitem_doneorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='priceSize',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
