# Generated by Django 4.2 on 2023-07-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_remove_buyitem_buyquantityao1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudrinks',
            name='hotAndCold',
        ),
    ]
