# Generated by Django 4.2.1 on 2023-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_menudrinks_hotandcold'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mema/'),
        ),
    ]
