# Generated by Django 4.2.1 on 2023-07-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_buyitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyitem',
            name='image',
        ),
    ]
