# Generated by Django 4.2.1 on 2023-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_remove_buyitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='PWD_discount',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=255, null=True),
        ),
    ]
