# Generated by Django 4.2.1 on 2023-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_buyitem_pwd_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='PWD_Id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
